### ISSUE TITLE
Hi, is the Eclipse model available?

### ISSUE THREAD

**Issue by tmliang** [sutdcv/SUTD-TrafficQA#1]
Thanks for your works! Is there any plan to release the source code of Eclipse and the checkpoints? We are interested in following up!

**Comment by AtharvanDogra** [comment]
Reopening this, Could I be provided with the code?
@tmliang If you got it, could you share?

**Comment by tmliang** [comment]
> Could I be provided with the code? @tmliang If you got it, could you share?

Yes, I have got  it. I'll forward it to your email.

**Comment by AtharvanDogra** [comment]
Thankyou very much

**Comment by DoubleSsh** [comment]
Hi.Could I be provided with the code?
@tmliang If you got it, could you share?

**Comment by DoubleSsh** [comment]
Hi.Could I be provided with the code?
@tmliang Could you share?Thank you so much

**Comment by guokan987** [comment]
Hi.Could I be provided with the code? Thanks you!!guokan.cn@gmail.com

**Comment by guokan987** [comment]
> Thankyou very much

Hi.Could I be provided with the code? Thanks you!![guokan.cn@gmail.com](mailto:guokan.cn@gmail.com)

**Comment by arandinglv** [comment]
Hi! Could I be provided with the Eclipse model? I will be grateful for your share. My email address: arandinglv@gmail.com
@tmliang
