### ISSUE TITLE
How to distinguish the reasoning task of a question?

### ISSUE THREAD

**Issue by TianboJi** [sutdcv/SUTD-TrafficQA#2]
In your paper, the dataset has six challenging traffic-related reasoning tasks: basic understanding, event forecasting, reverse reasoning, counterfactual inference, introspection, and attribution. However, such labels seem unavailable in the dataset. Can you provide the script for distinguishing them? Thank you.

**Comment by MarkHershey** [comment]
Hi @TianboJi , sorry for the late reply, we have updated the annotations to include the question types, please redownload it from our google drive folder and refer to our website for more information.
